"""add rate limits

Revision ID: 5192ad66ca0f
Revises: 20260614_0001
Create Date: 2026-06-14 01:57:44.604909
"""
from typing import Optional, Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5192ad66ca0f'
down_revision: Optional[str] = '20260614_0001'
branch_labels: Optional[Union[str, Sequence[str]]] = None
depends_on: Optional[Union[str, Sequence[str]]] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate_limits',
    sa.Column('client_key', sa.String(length=128), nullable=False),
    sa.Column('window_minute', sa.BigInteger(), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('client_key', 'window_minute')
    )
    op.create_index(op.f('ix_rate_limits_client_key'), 'rate_limits', ['client_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rate_limits_client_key'), table_name='rate_limits')
    op.drop_table('rate_limits')
    # ### end Alembic commands ###
